import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from argparse import ArgumentParser
import json

parser = ArgumentParser(prog='python pca-visualizer.py')
parser.add_argument('infile', help='input json file generated by simulator', type=str)
args = parser.parse_args()

if __name__ == '__main__':
    infile = open(args.infile, "r")

    dist_log = json.load(infile)
    virus_dist = dist_log['virus']
    antibody_dist = dist_log['antibody']

    fig, ax = plt.subplots()
    artists = []
    for data in virus_dist:
        container = ax.imshow(data)
        artists.append([container])
    
    ani = animation.ArtistAnimation(fig, artists, interval=50)
    plt.show()
    ani.save("./output.gif", writer="pillow")

    infile.close()